trigger: none

pool: 'Laptop-Agent-Pool'

variables:
  - group: GENERAL

stages:
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: BuildJob
        container: 
          image: 'harrison237/node-angular:v3'
          env:
            NODE_OPTIONS: '--experimental-require-module'
        displayName: 'Build and Test'
        steps:
          - checkout: self
          
          - script: |
              node -v
              npm -v

              if ! command -v pnpm &> /dev/null; then
                npm install -g pnpm
              else
                echo "pnpm ya está instalado"
              fi
            displayName: 'Verify node, npm and pnpm'

          - script: |
              pnpm install

              npx nx --version
            displayName: 'Install Dependencies with pnpm'

          - script: |
              pnpm run build:prod
            displayName: 'Build Application with pnpm'

          - script: |
              cd dist/gorenas-front/browser
              echo "[INFO] Current Folder is : $(pwd)"

              zip -r $(Build.SourcesDirectory)/gorenas-front-dist.zip ./*

              echo "[INFO] Compressed folder created at : $(Build.SourcesDirectory)/gorenas-front-dist.zip"

            displayName: 'Zip project folder folder for publishment'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'gorenas-front-dist.zip'
              ArtifactName: 'final-project'
            displayName: 'Publish compressed project folder'

          - task: CopyFiles@2
            inputs:
              Contents: |
                package.json
                pnpm-lock.yaml
                nx.json
                netlify.toml
              TargetFolder: '$(Build.ArtifactStagingDirectory)/package-files'
            displayName: 'Copy package files'
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/package-files'
              ArtifactName: 'package-files'
            displayName: 'Publish package files'

  - stage: Deploy
    displayName: 'Deploy Application'
    dependsOn: Build
    jobs:
      - deployment: DeployJob
        displayName: 'Deploy to Netlify'
        environment: 'development'
        container: 
          image: 'harrison237/node-angular:v3'
          env:
            NODE_OPTIONS: '--experimental-require-module'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: final-project
                  displayName: 'Download compiled project artifact'

                - download: current
                  artifact: package-files
                  displayName: 'Download package files artifact'
          
                - script: |
                    node -v
                    npm -v

                    if ! command -v pnpm &> /dev/null; then
                      npm install -g pnpm
                    else
                      echo "pnpm ya está instalado"
                    fi
                  displayName: 'Verify node, npm and pnpm'

                - script: |
                    pnpm install --save-dev netlify-cli
                  displayName: 'Install Dependencies with pnpm'

                - script: |
                    mkdir -p $(Build.SourcesDirectory)/to-deploy/

                    unzip -o $(Pipeline.Workspace)/final-project/gorenas-front-dist.zip -d $(Build.SourcesDirectory)/to-deploy/

                    ls -la
                    pwd
                  displayName: 'Unzip compiled project'

                - script: |
                    cp $(Pipeline.Workspace)/package-files/package.json $(Build.SourcesDirectory)/
                    cp $(Pipeline.Workspace)/package-files/pnpm-lock.yaml $(Build.SourcesDirectory)/
                    cp $(Pipeline.Workspace)/package-files/nx.json $(Build.SourcesDirectory)/
                    cp $(Pipeline.Workspace)/package-files/netlify.toml $(Build.SourcesDirectory)/to-deploy/

                    pnpm install --frozen-lockfile --prod
                  displayName: 'Copy instalation packages'

                - script: |
                    echo "[INFO] Netlify Project ID is: $NETLIFY_SITE_ID"

                    echo "\1f680 Deploying to Netlify..."
                    npx netlify deploy \
                      --dir=$(Build.SourcesDirectory)/to-deploy/ \
                      --auth=$NETLIFY_TOKEN \
                      --no-build \
                      --site=$NETLIFY_SITE_ID \
                      --prod
                  displayName: 'Deploy to Netlify'
                  env:
                    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
                    NETLIFY_TOKEN: $(NETLIFY_TOKEN)
              
  - stage: CleanUp
    displayName: 'Clean Up'
    dependsOn: [Build, Deploy]
    jobs:
      - job: CleanupJob
        displayName: 'Clean Workspace'
        condition: always()
        steps:
          - script: |
              echo "Limpiando workspace completo..."
              rm -rf $(Pipeline.Workspace)/*
              echo "Limpieza completada"
            displayName: 'Clean all workspace'
